server:
  port: 8082

spring:
  main:
    lazy-initialization: true
  cloud:
    openfeign:
      discovery:
        enabled: true
    loadbalancer:
      retry:
        enabled: true
  application:
    name: ORDER-SERVICE
    config:
      client-url: http://client-service:8084
      payment-url: http://payment-service:8086
    
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: order-service
    nonSecurePort: 8082

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      product-service:
        loggerLevel: FULL
      client-service:
        loggerLevel: BASIC
      payment-service:
        loggerLevel: BASIC

resilience4j.circuitbreaker:
  instances:
    productService:
      slidingWindowSize: 20
      failureRateThreshold: 80
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      minimumNumberOfCalls: 5
      ignoreExceptions:
        - java.lang.RuntimeException # Business exceptions are usually RuntimeException here

resilience4j.retry:
  instances:
    productService:
      maxAttempts: 3
      waitDuration: 1s
      retryExceptions:
        - feign.FeignException$ServiceUnavailable
        - feign.FeignException$InternalServerError



logging:
  level:
    com.ecommerce.order.service.client: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
